// prototype/frontOffice/src/app/components/EditaisPage.tsx
import { FileText, ChevronRight, Clock, Calendar, Users, ChevronDown } from 'lucide-react';
import { useState } from 'react';
import { DatePicker } from '@/app/components/DatePicker';
import { EditalDetalhePage } from '@/app/components/EditalDetalhePage';

export function EditaisPage() {
  const [selectedTipo, setSelectedTipo] = useState('Todos');
  const [selectedStatus, setSelectedStatus] = useState('Abertos');
  const [selectedDate, setSelectedDate] = useState('');
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [isStatusDropdownOpen, setIsStatusDropdownOpen] = useState(false);
  const [selectedEdital, setSelectedEdital] = useState<number | null>(null);

  const tipoOptions = [
    'Todos',
    'Carreira Científica',
    'Pesquisa',
    'Difusão do Conhecimento',
    'Extensão',
    'Inovação',
    'Chamadas Internacionais',
  ];

  const statusOptions = ['Abertos', 'Em Análise', 'Encerrados'];

  const editais = [
    {
      id: 1,
      numero: 'Edital Fapes Nº 27/2025',
      titulo: 'Apoio à Editoração e Publicação de Periódicos Científicos',
      descricao: 'Apoio financeiro para publicação de periódicos científicos de instituições do Espírito Santo.',
      prazo: '01/06/2026',
      status: 'Aberto',
      modalidade: 'Periódicos Científicos',
      inscritos: 42,
    },
    {
      id: 2,
      numero: 'Edital Fapes Nº 26/2025',
      titulo: 'Programa de Bolsas de Iniciação Científica - BPIG-IX',
      descricao: 'Concessão de bolsas de iniciação científica para estudantes de graduação.',
      prazo: '15/05/2026',
      status: 'Aberto',
      modalidade: 'Iniciação Científica',
      inscritos: 156,
    },
    {
      id: 3,
      numero: 'Edital Fapes Nº 25/2025',
      titulo: 'Apoio a Projetos de Pesquisa Aplicada em Inovação Tecnológica',
      descricao: 'Financiamento de projetos de pesquisa aplicada voltados para inovação tecnológica.',
      prazo: '30/04/2026',
      status: 'Aberto',
      modalidade: 'Pesquisa Aplicada',
      inscritos: 78,
    },
    {
      id: 4,
      numero: 'Edital Fapes Nº 24/2025',
      titulo: 'Programa de Apoio ao Desenvolvimento Científico Regional',
      descricao: 'Apoio a projetos de desenvolvimento científico em municípios do interior do estado.',
      prazo: '20/04/2026',
      status: 'Em análise',
      modalidade: 'Desenvolvimento Regional',
      inscritos: 34,
    },
    {
      id: 5,
      numero: 'Edital Fapes Nº 23/2025',
      titulo: 'Bolsas de Mestrado e Doutorado - PPG-ES',
      descricao: 'Concessão de bolsas para programas de pós-graduação stricto sensu.',
      prazo: '10/03/2026',
      status: 'Encerrado',
      modalidade: 'Pós-Graduação',
      inscritos: 203,
    },
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Aberto':
        return { bg: 'rgba(34, 197, 94, 0.1)', color: '#22c55e', border: 'rgba(34, 197, 94, 0.3)' };
      case 'Em análise':
        return { bg: 'rgba(59, 130, 246, 0.1)', color: '#3b82f6', border: 'rgba(59, 130, 246, 0.3)' };
      case 'Encerrado':
        return { bg: 'rgba(115, 115, 115, 0.1)', color: '#737373', border: 'rgba(115, 115, 115, 0.3)' };
      default:
        return { bg: 'var(--muted)', color: 'var(--muted-foreground)', border: 'var(--border)' };
    }
  };

  // If an edital is selected, show the detail page
  if (selectedEdital !== null) {
    const edital = editais.find((e) => e.id === selectedEdital);
    if (edital) {
      return (
        <EditalDetalhePage
          edital={edital}
          onBack={() => setSelectedEdital(null)}
        />
      );
    }
  }

  return (
    <div className="w-full px-4 md:px-8 py-8">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div 
                style={{ 
                  padding: '0.5rem',
                  backgroundColor: 'var(--primary)',
                  borderRadius: 'var(--radius)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <FileText size={20} style={{ color: 'var(--background)' }} />
              </div>
              <h1 style={{ color: 'var(--foreground)', margin: 0 }}>
                Editais
              </h1>
            </div>
            <p 
              style={{ 
                color: 'var(--muted-foreground)',
                fontSize: 'var(--text-sm)',
                fontWeight: 'var(--font-weight-normal)',
                margin: 0,
                marginLeft: '48px',
              }}
            >
              Acompanhe as chamadas e se inscreva.
            </p>
          </div>
          
          {/* Botão Demanda Induzida */}
          <button
            className="px-6 py-2.5 transition-all"
            style={{
              backgroundColor: 'var(--primary)',
              color: 'var(--primary-foreground)',
              border: 'none',
              borderRadius: 'var(--radius)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-semibold)',
              cursor: 'pointer',
              boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.opacity = '0.9';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.opacity = '1';
            }}
          >
            Demanda Induzida
          </button>
        </div>
      </div>

      {/* Divider */}
      <div
        style={{
          height: '1px',
          backgroundColor: 'var(--border)',
          marginBottom: '2rem',
        }}
      />

      {/* Filters Section */}
      <div className="flex flex-col md:flex-row md:items-end gap-4 mb-6">
        {/* Search Bar */}
        <div className="flex-1">
          <input
            type="text"
            placeholder="Buscar editais..."
            className="w-full px-4 py-2 border transition-colors"
            style={{
              backgroundColor: 'var(--input-background)',
              color: 'var(--foreground)',
              borderColor: 'var(--border)',
              borderRadius: 'var(--radius)',
              fontSize: 'var(--text-sm)',
            }}
          />
        </div>

        {/* Status Buttons */}
        <div className="relative" style={{ minWidth: '200px' }}>
          <label
            style={{
              display: 'block',
              color: 'var(--foreground)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-medium)',
              marginBottom: '0.5rem',
            }}
          >
            Status
          </label>
          <button
            className="w-full px-4 py-2 transition-colors flex items-center justify-between"
            style={{
              backgroundColor: 'var(--input-background)',
              color: 'var(--foreground)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-normal)',
              cursor: 'pointer',
              textAlign: 'left',
            }}
            onClick={() => setIsStatusDropdownOpen(!isStatusDropdownOpen)}
          >
            <span>{selectedStatus}</span>
            <ChevronDown size={16} style={{ flexShrink: 0 }} />
          </button>
          {isStatusDropdownOpen && (
            <div
              className="absolute top-full left-0 right-0 mt-1 overflow-hidden"
              style={{
                backgroundColor: 'var(--background)',
                borderColor: 'var(--border)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius)',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                zIndex: 50,
              }}
            >
              {statusOptions.map((status) => (
                <button
                  key={status}
                  className="w-full px-4 py-2 text-left transition-colors"
                  style={{
                    color: 'var(--foreground)',
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-normal)',
                    cursor: 'pointer',
                    backgroundColor: selectedStatus === status ? 'color-mix(in srgb, var(--primary) 10%, transparent)' : 'transparent',
                    border: 'none',
                  }}
                  onMouseEnter={(e) => {
                    if (selectedStatus !== status) {
                      e.currentTarget.style.backgroundColor = 'color-mix(in srgb, var(--primary) 5%, transparent)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (selectedStatus !== status) {
                      e.currentTarget.style.backgroundColor = 'transparent';
                    } else {
                      e.currentTarget.style.backgroundColor = 'color-mix(in srgb, var(--primary) 10%, transparent)';
                    }
                  }}
                  onClick={() => {
                    setSelectedStatus(status);
                    setIsStatusDropdownOpen(false);
                  }}
                >
                  {status}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Tipo Dropdown */}
        <div className="relative" style={{ minWidth: '200px' }}>
          <label
            style={{
              display: 'block',
              color: 'var(--foreground)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-medium)',
              marginBottom: '0.5rem',
            }}
          >
            Tipo
          </label>
          <button
            className="w-full px-4 py-2 transition-colors flex items-center justify-between"
            style={{
              backgroundColor: 'var(--input-background)',
              color: 'var(--foreground)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-normal)',
              cursor: 'pointer',
              textAlign: 'left',
            }}
            onClick={() => setIsDropdownOpen(!isDropdownOpen)}
          >
            <span>{selectedTipo}</span>
            <ChevronDown size={16} style={{ flexShrink: 0 }} />
          </button>
          {isDropdownOpen && (
            <div
              className="absolute top-full left-0 right-0 mt-1 overflow-hidden"
              style={{
                backgroundColor: 'var(--background)',
                borderColor: 'var(--border)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius)',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                zIndex: 50,
              }}
            >
              {tipoOptions.map((tipo) => (
                <button
                  key={tipo}
                  className="w-full px-4 py-2 text-left transition-colors"
                  style={{
                    color: 'var(--foreground)',
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-normal)',
                    cursor: 'pointer',
                    backgroundColor: selectedTipo === tipo ? 'color-mix(in srgb, var(--primary) 10%, transparent)' : 'transparent',
                    border: 'none',
                  }}
                  onMouseEnter={(e) => {
                    if (selectedTipo !== tipo) {
                      e.currentTarget.style.backgroundColor = 'color-mix(in srgb, var(--primary) 5%, transparent)';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (selectedTipo !== tipo) {
                      e.currentTarget.style.backgroundColor = 'transparent';
                    } else {
                      e.currentTarget.style.backgroundColor = 'color-mix(in srgb, var(--primary) 10%, transparent)';
                    }
                  }}
                  onClick={() => {
                    setSelectedTipo(tipo);
                    setIsDropdownOpen(false);
                  }}
                >
                  {tipo}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Date Picker */}
        <div className="relative" style={{ minWidth: '200px' }}>
          <label
            style={{
              display: 'block',
              color: 'var(--foreground)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-medium)',
              marginBottom: '0.5rem',
            }}
          >
            Data
          </label>
          <DatePicker
            selectedDate={selectedDate}
            onDateChange={setSelectedDate}
            placeholder="Todos"
            className="w-full px-4 py-2 transition-colors flex items-center justify-between"
            style={{
              backgroundColor: 'var(--input-background)',
              color: 'var(--foreground)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-normal)',
              cursor: 'pointer',
              textAlign: 'left',
            }}
          />
        </div>
      </div>

      {/* Editais List */}
      <div className="space-y-4">
        {editais.map((edital) => {
          const statusColors = getStatusColor(edital.status);
          
          return (
            <a
              key={edital.id}
              href="#"
              className="group block"
              style={{
                textDecoration: 'none',
              }}
              onClick={() => setSelectedEdital(edital.id)}
            >
              <div
                className="p-5 transition-all"
                style={{
                  backgroundColor: 'color-mix(in srgb, var(--primary) 3%, transparent)',
                  border: '1px solid color-mix(in srgb, var(--primary) 12%, transparent)',
                  borderRadius: 'var(--radius)',
                  cursor: 'pointer',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.backgroundColor = 'color-mix(in srgb, var(--primary) 8%, transparent)';
                  e.currentTarget.style.borderColor = 'color-mix(in srgb, var(--primary) 25%, transparent)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.backgroundColor = 'color-mix(in srgb, var(--primary) 3%, transparent)';
                  e.currentTarget.style.borderColor = 'color-mix(in srgb, var(--primary) 12%, transparent)';
                }}
              >
                <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
                  <div className="flex-1">
                    {/* Número e Status */}
                    <div className="flex flex-wrap items-center gap-3 mb-3">
                      <span
                        style={{
                          color: 'var(--primary)',
                          fontSize: 'var(--text-sm)',
                          fontWeight: 'var(--font-weight-semibold)',
                        }}
                      >
                        {edital.numero}
                      </span>
                      <span
                        className="inline-flex items-center px-2.5 py-1"
                        style={{
                          backgroundColor: statusColors.bg,
                          color: statusColors.color,
                          border: `1px solid ${statusColors.border}`,
                          borderRadius: '9999px',
                          fontSize: 'var(--text-xs)',
                          fontWeight: 'var(--font-weight-medium)',
                        }}
                      >
                        {edital.status}
                      </span>
                    </div>

                    {/* Título */}
                    <h1
                      style={{
                        color: 'var(--foreground)',
                        marginBottom: '0.5rem',
                      }}
                    >
                      {edital.titulo}
                    </h1>

                    {/* Descrição */}
                    <p
                      style={{
                        color: 'var(--muted-foreground)',
                        fontSize: 'var(--text-sm)',
                        fontWeight: 'var(--font-weight-normal)',
                        marginBottom: '1rem',
                      }}
                    >
                      {edital.descricao}
                    </p>

                    {/* Info Row */}
                    <div className="flex flex-wrap items-center gap-4">
                      <div className="flex items-center gap-1.5">
                        <Calendar size={14} style={{ color: 'var(--muted-foreground)' }} />
                        <span
                          style={{
                            color: 'var(--muted-foreground)',
                            fontSize: 'var(--text-sm)',
                            fontWeight: 'var(--font-weight-normal)',
                          }}
                        >
                          Inscrições até {edital.prazo}
                        </span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <Users size={14} style={{ color: 'var(--muted-foreground)' }} />
                        <span
                          style={{
                            color: 'var(--muted-foreground)',
                            fontSize: 'var(--text-sm)',
                            fontWeight: 'var(--font-weight-normal)',
                          }}
                        >
                          {edital.inscritos} inscritos
                        </span>
                      </div>
                      <span
                        className="inline-flex items-center px-2.5 py-1"
                        style={{
                          backgroundColor: 'color-mix(in srgb, var(--primary) 10%, transparent)',
                          color: 'var(--primary)',
                          borderRadius: 'var(--radius-sm)',
                          fontSize: 'var(--text-xs)',
                          fontWeight: 'var(--font-weight-medium)',
                        }}
                      >
                        {edital.modalidade}
                      </span>
                    </div>
                  </div>

                  {/* Arrow Icon */}
                  <div
                    className="transition-transform self-end md:self-auto"
                    style={{
                      color: 'var(--primary)',
                      flexShrink: 0,
                    }}
                  >
                    <ChevronRight size={20} />
                  </div>
                </div>
              </div>
            </a>
          );
        })}
      </div>

      {/* Empty State Message - Hidden when there are results */}
      {editais.length === 0 && (
        <div
          className="flex flex-col items-center justify-center py-16"
          style={{
            backgroundColor: 'color-mix(in srgb, var(--primary) 3%, transparent)',
            border: '1px solid color-mix(in srgb, var(--primary) 10%, transparent)',
            borderRadius: 'var(--radius)',
          }}
        >
          <FileText size={48} style={{ color: 'var(--muted-foreground)', marginBottom: '1rem' }} />
          <p
            style={{
              color: 'var(--muted-foreground)',
              fontSize: 'var(--text-base)',
              fontWeight: 'var(--font-weight-normal)',
              textAlign: 'center',
            }}
          >
            Nenhum edital encontrado
          </p>
        </div>
      )}
    </div>
  );
}

// prototype/frontOffice-vue/src/pages/EditaisPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { editais as editaisData, type Edital } from '@/data/editais'

const router = useRouter()

const selectedTipo = ref('Todos')
const selectedStatus = ref('Abertos')
const selectedDate = ref('')
const isDropdownOpen = ref(false)
const isStatusDropdownOpen = ref(false)
const searchQuery = ref('')

const tipoOptions = [
  'Todos',
  'Carreira Científica',
  'Pesquisa',
  'Difusão do Conhecimento',
  'Extensão',
  'Inovação',
  'Chamadas Internacionais',
]

const statusOptions = ['Abertos', 'Em Análise', 'Encerrados']

type StatusColor = { bg: string; color: string; border: string }

function getStatusColor(status: string): StatusColor {
  switch (status) {
    case 'Aberto':
    case 'Ativo':
      return { bg: 'rgba(34, 197, 94, 0.1)', color: '#22c55e', border: 'rgba(34, 197, 94, 0.3)' }
    case 'Em análise':
    case 'Em Análise':
      return { bg: 'rgba(59, 130, 246, 0.1)', color: '#3b82f6', border: 'rgba(59, 130, 246, 0.3)' }
    case 'Encerrado':
    case 'Encerrados':
      return { bg: 'rgba(100, 116, 139, 0.1)', color: '#64748b', border: 'rgba(100, 116, 139, 0.3)' }
    default:
      return { bg: 'var(--muted)', color: 'var(--muted-foreground)', border: 'var(--border)' }
  }
}

function matchesStatus(edital: Edital): boolean {
  if (selectedStatus.value === 'Abertos') return edital.status === 'Ativo' || edital.status === 'Aberto'
  if (selectedStatus.value === 'Em Análise') return edital.status === 'Em análise' || edital.status === 'Em Análise'
  if (selectedStatus.value === 'Encerrados') return edital.status === 'Encerrado' || edital.status === 'Encerrados'
  return true
}

const filteredEditais = computed(() =>
  editaisData.filter((e) => {
    if (selectedTipo.value !== 'Todos' && e.area !== selectedTipo.value) return false
    if (!matchesStatus(e)) return false
    if (searchQuery.value.trim()) {
      const q = searchQuery.value.toLowerCase()
      const hay = `${e.titulo} ${e.numero ?? ''} ${e.descricao} ${e.programa} ${e.area}`.toLowerCase()
      if (!hay.includes(q)) return false
    }
    return true
  })
)

function openEdital(id: number) {
  router.push(`/editais/${id}`)
}

function selectTipo(t: string) {
  selectedTipo.value = t
  isDropdownOpen.value = false
}

function selectStatus(s: string) {
  selectedStatus.value = s
  isStatusDropdownOpen.value = false
}
</script>

<template>
  <div class="w-full px-4 md:px-8 py-8">
    <!-- Header -->
    <div class="mb-6">
      <div class="flex items-center justify-between">
        <div>
          <div class="flex items-center gap-3 mb-2">
            <div
              :style="{
                padding: '0.5rem',
                backgroundColor: 'var(--primary)',
                borderRadius: 'var(--radius)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }"
            >
              <UIcon name="i-lucide-file-text" :style="{ color: 'var(--background)', width: '20px', height: '20px' }" />
            </div>
            <h1 :style="{ color: 'var(--foreground)', margin: 0 }">Editais</h1>
          </div>
          <p
            :style="{
              color: 'var(--muted-foreground)',
              fontSize: 'var(--text-sm)',
              fontWeight: 'var(--font-weight-normal)',
              margin: 0,
              marginLeft: '48px',
            }"
          >
            Acompanhe as chamadas e se inscreva.
          </p>
        </div>

        <UButton color="primary" size="md">Demanda Induzida</UButton>
      </div>
    </div>

    <!-- Divider -->
    <div :style="{ height: '1px', backgroundColor: 'var(--border)', marginBottom: '2rem' }" />

    <!-- Filters -->
    <div class="flex flex-col md:flex-row md:items-end gap-4 mb-6">
      <!-- Search -->
      <div class="flex-1">
        <UInput
          v-model="searchQuery"
          placeholder="Buscar editais..."
          icon="i-lucide-search"
          size="lg"
          class="w-full"
        />
      </div>

      <!-- Status -->
      <div class="relative" :style="{ minWidth: '200px' }">
        <label
          :style="{
            display: 'block',
            color: 'var(--foreground)',
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--font-weight-medium)',
            marginBottom: '0.5rem',
          }"
        >Status</label>
        <button
          type="button"
          class="w-full px-4 py-2 flex items-center justify-between"
          :style="{
            backgroundColor: 'var(--input-background)',
            color: 'var(--foreground)',
            border: '1px solid var(--border)',
            borderRadius: 'var(--radius)',
            fontSize: 'var(--text-sm)',
            cursor: 'pointer',
            textAlign: 'left',
          }"
          @click="isStatusDropdownOpen = !isStatusDropdownOpen"
        >
          <span>{{ selectedStatus }}</span>
          <UIcon name="i-lucide-chevron-down" :style="{ width: '16px', height: '16px', flexShrink: 0 }" />
        </button>
        <div
          v-if="isStatusDropdownOpen"
          class="absolute top-full left-0 right-0 mt-1 overflow-hidden"
          :style="{
            backgroundColor: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: 'var(--radius)',
            boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)',
            zIndex: 50,
          }"
        >
          <button
            v-for="status in statusOptions"
            :key="status"
            type="button"
            class="w-full px-4 py-2 text-left"
            :style="{
              color: 'var(--foreground)',
              fontSize: 'var(--text-sm)',
              cursor: 'pointer',
              backgroundColor: selectedStatus === status
                ? 'color-mix(in srgb, var(--primary) 10%, transparent)'
                : 'transparent',
              border: 'none',
            }"
            @click="selectStatus(status)"
          >
            {{ status }}
          </button>
        </div>
      </div>

      <!-- Tipo -->
      <div class="relative" :style="{ minWidth: '200px' }">
        <label
          :style="{
            display: 'block',
            color: 'var(--foreground)',
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--font-weight-medium)',
            marginBottom: '0.5rem',
          }"
        >Tipo</label>
        <button
          type="button"
          class="w-full px-4 py-2 flex items-center justify-between"
          :style="{
            backgroundColor: 'var(--input-background)',
            color: 'var(--foreground)',
            border: '1px solid var(--border)',
            borderRadius: 'var(--radius)',
            fontSize: 'var(--text-sm)',
            cursor: 'pointer',
            textAlign: 'left',
          }"
          @click="isDropdownOpen = !isDropdownOpen"
        >
          <span>{{ selectedTipo }}</span>
          <UIcon name="i-lucide-chevron-down" :style="{ width: '16px', height: '16px', flexShrink: 0 }" />
        </button>
        <div
          v-if="isDropdownOpen"
          class="absolute top-full left-0 right-0 mt-1 overflow-hidden"
          :style="{
            backgroundColor: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: 'var(--radius)',
            boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)',
            zIndex: 50,
          }"
        >
          <button
            v-for="tipo in tipoOptions"
            :key="tipo"
            type="button"
            class="w-full px-4 py-2 text-left"
            :style="{
              color: 'var(--foreground)',
              fontSize: 'var(--text-sm)',
              cursor: 'pointer',
              backgroundColor: selectedTipo === tipo
                ? 'color-mix(in srgb, var(--primary) 10%, transparent)'
                : 'transparent',
              border: 'none',
            }"
            @click="selectTipo(tipo)"
          >
            {{ tipo }}
          </button>
        </div>
      </div>

      <!-- Data (DatePicker deferred -> placeholder UInput type=date) -->
      <div class="relative" :style="{ minWidth: '200px' }">
        <label
          :style="{
            display: 'block',
            color: 'var(--foreground)',
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--font-weight-medium)',
            marginBottom: '0.5rem',
          }"
        >Data</label>
        <UInput v-model="selectedDate" type="date" size="lg" class="w-full" />
      </div>
    </div>

    <!-- Editais List -->
    <div class="space-y-4">
      <a
        v-for="edital in filteredEditais"
        :key="edital.id"
        href="#"
        class="group block"
        :style="{ textDecoration: 'none' }"
        @click.prevent="openEdital(edital.id)"
      >
        <div
          class="p-5 transition-all"
          :style="{
            backgroundColor: 'color-mix(in srgb, var(--primary) 3%, transparent)',
            border: '1px solid color-mix(in srgb, var(--primary) 12%, transparent)',
            borderRadius: 'var(--radius)',
            cursor: 'pointer',
          }"
        >
          <div class="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
            <div class="flex-1">
              <div class="flex flex-wrap items-center gap-3 mb-3">
                <span
                  :style="{
                    color: 'var(--primary)',
                    fontSize: 'var(--text-sm)',
                    fontWeight: 'var(--font-weight-semibold)',
                  }"
                >{{ edital.numero ?? `Edital #${edital.id}` }}</span>
                <span
                  class="inline-flex items-center px-2.5 py-1"
                  :style="{
                    backgroundColor: getStatusColor(edital.status).bg,
                    color: getStatusColor(edital.status).color,
                    border: `1px solid ${getStatusColor(edital.status).border}`,
                    borderRadius: '9999px',
                    fontSize: 'var(--text-xs)',
                    fontWeight: 'var(--font-weight-medium)',
                  }"
                >{{ edital.status }}</span>
              </div>

              <h2 :style="{ color: 'var(--foreground)', marginBottom: '0.5rem' }">
                {{ edital.titulo }}
              </h2>

              <p
                :style="{
                  color: 'var(--muted-foreground)',
                  fontSize: 'var(--text-sm)',
                  fontWeight: 'var(--font-weight-normal)',
                  marginBottom: '1rem',
                }"
              >{{ edital.descricao }}</p>

              <div class="flex flex-wrap items-center gap-4">
                <div class="flex items-center gap-1.5">
                  <UIcon name="i-lucide-calendar" :style="{ color: 'var(--muted-foreground)', width: '14px', height: '14px' }" />
                  <span
                    :style="{
                      color: 'var(--muted-foreground)',
                      fontSize: 'var(--text-sm)',
                    }"
                  >Inscrições até {{ edital.prazo }}</span>
                </div>
                <div class="flex items-center gap-1.5">
                  <UIcon name="i-lucide-users" :style="{ color: 'var(--muted-foreground)', width: '14px', height: '14px' }" />
                  <span
                    :style="{
                      color: 'var(--muted-foreground)',
                      fontSize: 'var(--text-sm)',
                    }"
                  >{{ edital.vagas }} vagas</span>
                </div>
                <span
                  class="inline-flex items-center px-2.5 py-1"
                  :style="{
                    backgroundColor: 'color-mix(in srgb, var(--primary) 10%, transparent)',
                    color: 'var(--primary)',
                    borderRadius: 'var(--radius-sm)',
                    fontSize: 'var(--text-xs)',
                    fontWeight: 'var(--font-weight-medium)',
                  }"
                >{{ edital.area }}</span>
              </div>
            </div>

            <div
              class="transition-transform self-end md:self-auto"
              :style="{ color: 'var(--primary)', flexShrink: 0 }"
            >
              <UIcon name="i-lucide-chevron-right" :style="{ width: '20px', height: '20px' }" />
            </div>
          </div>
        </div>
      </a>
    </div>

    <!-- Empty -->
    <div
      v-if="filteredEditais.length === 0"
      class="flex flex-col items-center justify-center py-16"
      :style="{
        backgroundColor: 'color-mix(in srgb, var(--primary) 3%, transparent)',
        border: '1px solid color-mix(in srgb, var(--primary) 10%, transparent)',
        borderRadius: 'var(--radius)',
      }"
    >
      <UIcon name="i-lucide-file-text" :style="{ color: 'var(--muted-foreground)', width: '48px', height: '48px', marginBottom: '1rem' }" />
      <p
        :style="{
          color: 'var(--muted-foreground)',
          fontSize: 'var(--text-base)',
          textAlign: 'center',
        }"
      >Nenhum edital encontrado</p>
    </div>
  </div>
</template>
